# coding: utf-8

# flake8: noqa
"""
    Simple FIDO API

    This is the FIDO API  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: ruhma@metrarc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.allow_credentials import AllowCredentials
from swagger_client.models.allow_credentials_inner import AllowCredentialsInner
from swagger_client.models.attestation import Attestation
from swagger_client.models.attestation_object import AttestationObject
from swagger_client.models.authentication_request import AuthenticationRequest
from swagger_client.models.authenticator_assertion_response import AuthenticatorAssertionResponse
from swagger_client.models.authenticator_assertion_response_response import AuthenticatorAssertionResponseResponse
from swagger_client.models.authenticator_attestation_response import AuthenticatorAttestationResponse
from swagger_client.models.authenticator_selection import AuthenticatorSelection
from swagger_client.models.challenge import Challenge
from swagger_client.models.client_data_json import ClientDataJSON
from swagger_client.models.credential_id import CredentialId
from swagger_client.models.exclude_credentials import ExcludeCredentials
from swagger_client.models.exclude_credentials_inner import ExcludeCredentialsInner
from swagger_client.models.extensions import Extensions
from swagger_client.models.pub_key_cred_params import PubKeyCredParams
from swagger_client.models.public_key_cred_params_inner import PublicKeyCredParamsInner
from swagger_client.models.public_key_credential_creation_options import PublicKeyCredentialCreationOptions
from swagger_client.models.public_key_credential_request_options import PublicKeyCredentialRequestOptions
from swagger_client.models.registration_request import RegistrationRequest
from swagger_client.models.rp import Rp
from swagger_client.models.server_response import ServerResponse
from swagger_client.models.start_authentication_response import StartAuthenticationResponse
from swagger_client.models.timeout import Timeout
from swagger_client.models.user import User
from swagger_client.models.user_verification import UserVerification
