# coding: utf-8

"""
    Simple FIDO API

    This is the FIDO API  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: ruhma@metrarc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AttestationObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authenticator_data': 'str',
        'attestation_statement': 'str'
    }

    attribute_map = {
        'authenticator_data': 'authenticatorData',
        'attestation_statement': 'attestationStatement'
    }

    def __init__(self, authenticator_data=None, attestation_statement=None):  # noqa: E501
        """AttestationObject - a model defined in Swagger"""  # noqa: E501
        self._authenticator_data = None
        self._attestation_statement = None
        self.discriminator = None
        if authenticator_data is not None:
            self.authenticator_data = authenticator_data
        if attestation_statement is not None:
            self.attestation_statement = attestation_statement

    @property
    def authenticator_data(self):
        """Gets the authenticator_data of this AttestationObject.  # noqa: E501


        :return: The authenticator_data of this AttestationObject.  # noqa: E501
        :rtype: str
        """
        return self._authenticator_data

    @authenticator_data.setter
    def authenticator_data(self, authenticator_data):
        """Sets the authenticator_data of this AttestationObject.


        :param authenticator_data: The authenticator_data of this AttestationObject.  # noqa: E501
        :type: str
        """

        self._authenticator_data = authenticator_data

    @property
    def attestation_statement(self):
        """Gets the attestation_statement of this AttestationObject.  # noqa: E501


        :return: The attestation_statement of this AttestationObject.  # noqa: E501
        :rtype: str
        """
        return self._attestation_statement

    @attestation_statement.setter
    def attestation_statement(self, attestation_statement):
        """Sets the attestation_statement of this AttestationObject.


        :param attestation_statement: The attestation_statement of this AttestationObject.  # noqa: E501
        :type: str
        """

        self._attestation_statement = attestation_statement

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AttestationObject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttestationObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
