# coding: utf-8

"""
    Simple FIDO API

    This is the FIDO API  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: ruhma@metrarc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AuthenticatorSelection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'require_resident_key': 'bool',
        'user_verification': 'UserVerification'
    }

    attribute_map = {
        'require_resident_key': 'requireResidentKey',
        'user_verification': 'userVerification'
    }

    def __init__(self, require_resident_key=None, user_verification=None):  # noqa: E501
        """AuthenticatorSelection - a model defined in Swagger"""  # noqa: E501
        self._require_resident_key = None
        self._user_verification = None
        self.discriminator = None
        if require_resident_key is not None:
            self.require_resident_key = require_resident_key
        if user_verification is not None:
            self.user_verification = user_verification

    @property
    def require_resident_key(self):
        """Gets the require_resident_key of this AuthenticatorSelection.  # noqa: E501


        :return: The require_resident_key of this AuthenticatorSelection.  # noqa: E501
        :rtype: bool
        """
        return self._require_resident_key

    @require_resident_key.setter
    def require_resident_key(self, require_resident_key):
        """Sets the require_resident_key of this AuthenticatorSelection.


        :param require_resident_key: The require_resident_key of this AuthenticatorSelection.  # noqa: E501
        :type: bool
        """

        self._require_resident_key = require_resident_key

    @property
    def user_verification(self):
        """Gets the user_verification of this AuthenticatorSelection.  # noqa: E501


        :return: The user_verification of this AuthenticatorSelection.  # noqa: E501
        :rtype: UserVerification
        """
        return self._user_verification

    @user_verification.setter
    def user_verification(self, user_verification):
        """Sets the user_verification of this AuthenticatorSelection.


        :param user_verification: The user_verification of this AuthenticatorSelection.  # noqa: E501
        :type: UserVerification
        """

        self._user_verification = user_verification

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AuthenticatorSelection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AuthenticatorSelection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
