# coding: utf-8

"""
    Simple FIDO API

    This is the FIDO API  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: ruhma@metrarc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class ExcludeCredentialsInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'public_key_credential_type': 'int',
        'credential_id': 'CredentialId'
    }

    attribute_map = {
        'public_key_credential_type': 'PublicKeyCredentialType',
        'credential_id': 'credentialId'
    }

    def __init__(self, public_key_credential_type=None, credential_id=None):  # noqa: E501
        """ExcludeCredentialsInner - a model defined in Swagger"""  # noqa: E501
        self._public_key_credential_type = None
        self._credential_id = None
        self.discriminator = None
        if public_key_credential_type is not None:
            self.public_key_credential_type = public_key_credential_type
        if credential_id is not None:
            self.credential_id = credential_id

    @property
    def public_key_credential_type(self):
        """Gets the public_key_credential_type of this ExcludeCredentialsInner.  # noqa: E501


        :return: The public_key_credential_type of this ExcludeCredentialsInner.  # noqa: E501
        :rtype: int
        """
        return self._public_key_credential_type

    @public_key_credential_type.setter
    def public_key_credential_type(self, public_key_credential_type):
        """Sets the public_key_credential_type of this ExcludeCredentialsInner.


        :param public_key_credential_type: The public_key_credential_type of this ExcludeCredentialsInner.  # noqa: E501
        :type: int
        """

        self._public_key_credential_type = public_key_credential_type

    @property
    def credential_id(self):
        """Gets the credential_id of this ExcludeCredentialsInner.  # noqa: E501


        :return: The credential_id of this ExcludeCredentialsInner.  # noqa: E501
        :rtype: CredentialId
        """
        return self._credential_id

    @credential_id.setter
    def credential_id(self, credential_id):
        """Sets the credential_id of this ExcludeCredentialsInner.


        :param credential_id: The credential_id of this ExcludeCredentialsInner.  # noqa: E501
        :type: CredentialId
        """

        self._credential_id = credential_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExcludeCredentialsInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExcludeCredentialsInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
