# coding: utf-8

"""
    Simple FIDO API

    This is the FIDO API  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: ruhma@metrarc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class PublicKeyCredParamsInner(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'alg': 'int',
        'type': 'str'
    }

    attribute_map = {
        'alg': 'alg',
        'type': 'type'
    }

    def __init__(self, alg=None, type=None):  # noqa: E501
        """PublicKeyCredParamsInner - a model defined in Swagger"""  # noqa: E501
        self._alg = None
        self._type = None
        self.discriminator = None
        self.alg = alg
        self.type = type

    @property
    def alg(self):
        """Gets the alg of this PublicKeyCredParamsInner.  # noqa: E501


        :return: The alg of this PublicKeyCredParamsInner.  # noqa: E501
        :rtype: int
        """
        return self._alg

    @alg.setter
    def alg(self, alg):
        """Sets the alg of this PublicKeyCredParamsInner.


        :param alg: The alg of this PublicKeyCredParamsInner.  # noqa: E501
        :type: int
        """
        if alg is None:
            raise ValueError("Invalid value for `alg`, must not be `None`")  # noqa: E501

        self._alg = alg

    @property
    def type(self):
        """Gets the type of this PublicKeyCredParamsInner.  # noqa: E501


        :return: The type of this PublicKeyCredParamsInner.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PublicKeyCredParamsInner.


        :param type: The type of this PublicKeyCredParamsInner.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PublicKeyCredParamsInner, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PublicKeyCredParamsInner):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
