# coding: utf-8

"""
    Simple FIDO API

    This is the FIDO API  # noqa: E501

    OpenAPI spec version: 2.0
    Contact: ruhma@metrarc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class StartAuthenticationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'public_key_credential_request_options': 'PublicKeyCredentialRequestOptions',
        'username': 'str'
    }

    attribute_map = {
        'public_key_credential_request_options': 'publicKeyCredentialRequestOptions',
        'username': 'username'
    }

    def __init__(self, public_key_credential_request_options=None, username=None):  # noqa: E501
        """StartAuthenticationResponse - a model defined in Swagger"""  # noqa: E501
        self._public_key_credential_request_options = None
        self._username = None
        self.discriminator = None
        if public_key_credential_request_options is not None:
            self.public_key_credential_request_options = public_key_credential_request_options
        if username is not None:
            self.username = username

    @property
    def public_key_credential_request_options(self):
        """Gets the public_key_credential_request_options of this StartAuthenticationResponse.  # noqa: E501


        :return: The public_key_credential_request_options of this StartAuthenticationResponse.  # noqa: E501
        :rtype: PublicKeyCredentialRequestOptions
        """
        return self._public_key_credential_request_options

    @public_key_credential_request_options.setter
    def public_key_credential_request_options(self, public_key_credential_request_options):
        """Sets the public_key_credential_request_options of this StartAuthenticationResponse.


        :param public_key_credential_request_options: The public_key_credential_request_options of this StartAuthenticationResponse.  # noqa: E501
        :type: PublicKeyCredentialRequestOptions
        """

        self._public_key_credential_request_options = public_key_credential_request_options

    @property
    def username(self):
        """Gets the username of this StartAuthenticationResponse.  # noqa: E501


        :return: The username of this StartAuthenticationResponse.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this StartAuthenticationResponse.


        :param username: The username of this StartAuthenticationResponse.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(StartAuthenticationResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, StartAuthenticationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
